### ISSUE TITLE
Question about Dytox experiments (Table 8 in ICCV paper).

### ISSUE THREAD

**Issue by tjdhg456** [scok30/MAE-CIL#1]
Hi! thank you for your great works.
In the table 8, you mentioned that 25% patch memory additionally improved the dytox performance.

For this experiment, you need additional masking augmentation during training?
If not, then how original vit model can be trained with masked memory without additional masking augmentation?

Thank you!

**Comment by scok30** [comment]
Thank you for your question. When we replace the replay buffer with Dytox, the current task data uses the complete images (without mask augmentation), and the replay buffer uses mask patches. During fine-tuning, due to the inconsistent data formats, we alternate between using the current task data and the replay buffer data for gradient updates.

**Comment by tjdhg456** [comment]
Thank you for your kind and fast reply.

Can you share the code about that parts? I have some idea to advance the methods.
Also, supplementary file is not attached to arxiv version.
Can you upload it also?

Because your approach is so interesting, I'd like to experiments your ideas.
Thank you very much!!

**Comment by scok30** [comment]
Thank you for your interest in our work. Due to our recent efforts to expand our research into journals, we may not have the resources to rebuild some of the previous ablation experiments. Adding 8000 masked replay samples on top of DyTox is actually not a complex task; it only requires modifications to the training process during buffer management and fine-tuning. This performance enhancement, as mentioned by some previous reviewers, is likely due to the increase in information in the replay buffer, even though each sample only retains a quarter of the data.

**Comment by tjdhg456** [comment]
Thank you for your reply. I already modified the original dytox code, but failed to achieve that performances. There might be some other reasons but I'll give it a try again.
Thank you again for your kind reply.
